# Generated by Django 3.1.4 on 2022-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '15. Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '14. Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '13. Chi tiết đơn hàng'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='percent',
        ),
        migrations.AddField(
            model_name='event',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
