# Generated by Django 3.1.4 on 2022-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220412_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='gift',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance',
            field=models.DateTimeField(),
        ),
    ]
