# Generated by Django 3.1.4 on 2022-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220412_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '14. Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '13. Đơn hàng'},
        ),
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
