# Generated by Django 3.1.4 on 2022-04-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220413_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
