# Generated by Django 3.1.4 on 2022-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_color_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
