# Generated by Django 3.1.4 on 2022-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discountcode_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='insurance',
            new_name='time_insurance',
        ),
        migrations.AddField(
            model_name='insurance',
            name='product_insurance',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
